// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Backends.Direct3D11
{
    public unsafe static partial class Globals
    {
        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_ImplDX11_Init", ExactSpelling = true)]
        private static extern byte ImGui_ImplDX11_Init_PInvoke(ID3D11Device* device, ID3D11DeviceContext* device_context);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ImGui_ImplDX11_Init(ID3D11Device* device, ID3D11DeviceContext* device_context)
        {
            byte __result;

            __result = ImGui_ImplDX11_Init_PInvoke(device, device_context);

            return Unsafe.As<byte, bool>(ref __result);
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ImGui_ImplDX11_Shutdown();

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ImGui_ImplDX11_NewFrame();

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ImGui_ImplDX11_RenderDrawData(ImDrawData* draw_data);

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ImGui_ImplDX11_InvalidateDeviceObjects();

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_ImplDX11_CreateDeviceObjects", ExactSpelling = true)]
        private static extern byte ImGui_ImplDX11_CreateDeviceObjects_PInvoke();

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ImGui_ImplDX11_CreateDeviceObjects()
        {
            byte __result;

            __result = ImGui_ImplDX11_CreateDeviceObjects_PInvoke();

            return Unsafe.As<byte, bool>(ref __result);
        }
    }
}
