// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Numerics;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public unsafe partial struct ImDrawVert
    {
        [FieldOffset(0)] public Vector2 pos;

        [FieldOffset(8)] public Vector2 uv;

        [FieldOffset(16)] public uint col;
    }
}
