// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public unsafe partial struct ImDrawCmd
    {
        [FieldOffset(0)] public Vector4 ClipRect;

        [FieldOffset(16)] public void* TextureId;

        [FieldOffset(24)] public uint VtxOffset;

        [FieldOffset(28)] public uint IdxOffset;

        [FieldOffset(32)] public uint ElemCount;

        [FieldOffset(40)] public delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void> UserCallback;

        [FieldOffset(48)] public void* UserCallbackData;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper11", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImDrawCmd* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImDrawCmd()
        {
            fixed (ImDrawCmd* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetTexID@ImDrawCmd@@QEBAPEAXXZ", ExactSpelling = true)]
        private static extern void* GetTexID_PInvoke(ImDrawCmd* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void* GetTexID()
        {
            fixed (ImDrawCmd* @this = &this)
            { return GetTexID_PInvoke(@this); }
        }
    }
}
