// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImFontAtlasCustomRect
    {
        [FieldOffset(0)] public ushort Width;

        [FieldOffset(2)] public ushort Height;

        [FieldOffset(4)] public ushort X;

        [FieldOffset(6)] public ushort Y;

        [FieldOffset(8)] public uint GlyphID;

        [FieldOffset(12)] public float GlyphAdvanceX;

        [FieldOffset(16)] public Vector2 GlyphOffset;

        [FieldOffset(24)] public ImFont* Font;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper18", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImFontAtlasCustomRect* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImFontAtlasCustomRect()
        {
            fixed (ImFontAtlasCustomRect* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?IsPacked@ImFontAtlasCustomRect@@QEBA_NXZ", ExactSpelling = true)]
        private static extern byte IsPacked_PInvoke(ImFontAtlasCustomRect* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool IsPacked()
        {
            byte __result;

            fixed (ImFontAtlasCustomRect* @this = &this)
            { __result = IsPacked_PInvoke(@this); }

            return Unsafe.As<byte, bool>(ref __result);
        }
    }
}
