// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 96)]
    public unsafe partial struct ImGuiViewport
    {
        [FieldOffset(0)] public uint ID;

        [FieldOffset(4)] public ImGuiViewportFlags Flags;

        [FieldOffset(8)] public Vector2 Pos;

        [FieldOffset(16)] public Vector2 Size;

        [FieldOffset(24)] public Vector2 WorkPos;

        [FieldOffset(32)] public Vector2 WorkSize;

        [FieldOffset(40)] public float DpiScale;

        [FieldOffset(44)] public uint ParentViewportId;

        [FieldOffset(48)] public ImDrawData* DrawData;

        [FieldOffset(56)] public void* RendererUserData;

        [FieldOffset(64)] public void* PlatformUserData;

        [FieldOffset(72)] public void* PlatformHandle;

        [FieldOffset(80)] public void* PlatformHandleRaw;

        [FieldOffset(88)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestMove;

        [FieldOffset(89)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestResize;

        [FieldOffset(90)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestClose;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper19", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiViewport* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiViewport()
        {
            fixed (ImGuiViewport* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper20", ExactSpelling = true)]
        private static extern void Destructor_PInvoke(ImGuiViewport* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (ImGuiViewport* @this = &this)
            { Destructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetCenter@ImGuiViewport@@QEBA?AUImVec2@@XZ", ExactSpelling = true)]
        private static extern Vector2* GetCenter_PInvoke(ImGuiViewport* @this, Vector2* __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Vector2 GetCenter()
        {
            Vector2 __returnBuffer;

            fixed (ImGuiViewport* @this = &this)
            { GetCenter_PInvoke(@this, &__returnBuffer); }

            return __returnBuffer;
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetWorkCenter@ImGuiViewport@@QEBA?AUImVec2@@XZ", ExactSpelling = true)]
        private static extern Vector2* GetWorkCenter_PInvoke(ImGuiViewport* @this, Vector2* __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Vector2 GetWorkCenter()
        {
            Vector2 __returnBuffer;

            fixed (ImGuiViewport* @this = &this)
            { GetWorkCenter_PInvoke(@this, &__returnBuffer); }

            return __returnBuffer;
        }
    }
}
