// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 36)]
    public unsafe partial struct ImGuiPlatformMonitor
    {
        [FieldOffset(0)] public Vector2 MainPos;

        [FieldOffset(8)] public Vector2 MainSize;

        [FieldOffset(16)] public Vector2 WorkPos;

        [FieldOffset(24)] public Vector2 WorkSize;

        [FieldOffset(32)] public float DpiScale;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper22", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiPlatformMonitor* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiPlatformMonitor()
        {
            fixed (ImGuiPlatformMonitor* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
