// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public unsafe partial struct ImGuiOnceUponAFrame
    {
        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper4", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiOnceUponAFrame* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiOnceUponAFrame()
        {
            fixed (ImGuiOnceUponAFrame* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [FieldOffset(0)] public int RefFrame;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??BImGuiOnceUponAFrame@@QEBA_NXZ", ExactSpelling = true)]
        private static extern byte ____ConversionOperator_bool_PInvoke(ImGuiOnceUponAFrame* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool ____ConversionOperator_bool()
        {
            byte __result;

            fixed (ImGuiOnceUponAFrame* @this = &this)
            { __result = ____ConversionOperator_bool_PInvoke(@this); }

            return Unsafe.As<byte, bool>(ref __result);
        }
    }
}
