// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Numerics;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImGuiSizeCallbackData
    {
        [FieldOffset(0)] public void* UserData;

        [FieldOffset(8)] public Vector2 Pos;

        [FieldOffset(16)] public Vector2 CurrentSize;

        [FieldOffset(24)] public Vector2 DesiredSize;
    }
}
