// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImGuiPlatformImeData
    {
        [FieldOffset(0)] [MarshalAs(UnmanagedType.I1)] public bool WantVisible;

        [FieldOffset(4)] public Vector2 InputPos;

        [FieldOffset(12)] public float InputLineHeight;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper23", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiPlatformImeData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiPlatformImeData()
        {
            fixed (ImGuiPlatformImeData* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
