// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImGuiKeyData
    {
        [FieldOffset(0)] [MarshalAs(UnmanagedType.I1)] public bool Down;

        [FieldOffset(4)] public float DownDuration;

        [FieldOffset(8)] public float DownDurationPrev;

        [FieldOffset(12)] public float AnalogValue;
    }
}
