// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 28)]
    public unsafe partial struct ImGuiWindowClass
    {
        [FieldOffset(0)] public uint ClassId;

        [FieldOffset(4)] public uint ParentViewportId;

        [FieldOffset(8)] public ImGuiViewportFlags ViewportFlagsOverrideSet;

        [FieldOffset(12)] public ImGuiViewportFlags ViewportFlagsOverrideClear;

        [FieldOffset(16)] public ImGuiTabItemFlags TabItemFlagsOverrideSet;

        [FieldOffset(20)] public ImGuiDockNodeFlags DockNodeFlagsOverrideSet;

        [FieldOffset(24)] [MarshalAs(UnmanagedType.I1)] public bool DockingAlwaysTabBar;

        [FieldOffset(25)] [MarshalAs(UnmanagedType.I1)] public bool DockingAllowUnclassed;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper0", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiWindowClass* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiWindowClass()
        {
            fixed (ImGuiWindowClass* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
