// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.DearImGui.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImDrawDataBuilder
    {
        [FieldOffset(0)] public ConstantArray_ImVector__UNICODE_003C__ImDrawList__UNICODE_0020____UNICODE_002A____UNICODE_003E___2 Layers;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Clear@ImDrawDataBuilder@@QEAAXXZ", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?ClearFreeMemory@ImDrawDataBuilder@@QEAAXXZ", ExactSpelling = true)]
        private static extern void ClearFreeMemory_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ClearFreeMemory()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { ClearFreeMemory_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetDrawListCount@ImDrawDataBuilder@@QEBAHXZ", ExactSpelling = true)]
        private static extern int GetDrawListCount_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int GetDrawListCount()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { return GetDrawListCount_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?FlattenIntoSingleLayer@ImDrawDataBuilder@@QEAAXXZ", ExactSpelling = true)]
        private static extern void FlattenIntoSingleLayer_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void FlattenIntoSingleLayer()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { FlattenIntoSingleLayer_PInvoke(@this); }
        }
    }
}
