// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.DearImGui.Infrastructure;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct ImFontBuilderIO
    {
        [FieldOffset(0)] public delegate* unmanaged[Cdecl]<ImFontAtlas*, NativeBoolean> FontBuilder_Build;
    }
}
