// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 18)]
    public unsafe partial struct ImGuiStackSizes
    {
        [FieldOffset(0)] public short SizeOfIDStack;

        [FieldOffset(2)] public short SizeOfColorStack;

        [FieldOffset(4)] public short SizeOfStyleVarStack;

        [FieldOffset(6)] public short SizeOfFontStack;

        [FieldOffset(8)] public short SizeOfFocusScopeStack;

        [FieldOffset(10)] public short SizeOfGroupStack;

        [FieldOffset(12)] public short SizeOfItemFlagsStack;

        [FieldOffset(14)] public short SizeOfBeginPopupStack;

        [FieldOffset(16)] public short SizeOfDisabledStack;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper38", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStackSizes* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiStackSizes()
        {
            fixed (ImGuiStackSizes* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?SetToCurrentState@ImGuiStackSizes@@QEAAXXZ", ExactSpelling = true)]
        private static extern void SetToCurrentState_PInvoke(ImGuiStackSizes* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetToCurrentState()
        {
            fixed (ImGuiStackSizes* @this = &this)
            { SetToCurrentState_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?CompareWithCurrentState@ImGuiStackSizes@@QEAAXXZ", ExactSpelling = true)]
        private static extern void CompareWithCurrentState_PInvoke(ImGuiStackSizes* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CompareWithCurrentState()
        {
            fixed (ImGuiStackSizes* @this = &this)
            { CompareWithCurrentState_PInvoke(@this); }
        }
    }
}
