// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.DearImGui.Internal
{
    public enum ImGuiComboFlagsPrivate_
    {
        ImGuiComboFlags_CustomPreview = 1048576
    }
}
