// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImGuiWindowSettings
    {
        [FieldOffset(0)] public uint ID;

        [FieldOffset(4)] public (short x, short y) Pos;

        [FieldOffset(8)] public (short x, short y) Size;

        [FieldOffset(12)] public (short x, short y) ViewportPos;

        [FieldOffset(16)] public uint ViewportId;

        [FieldOffset(20)] public uint DockId;

        [FieldOffset(24)] public uint ClassId;

        [FieldOffset(28)] public short DockOrder;

        [FieldOffset(30)] [MarshalAs(UnmanagedType.I1)] public bool Collapsed;

        [FieldOffset(31)] [MarshalAs(UnmanagedType.I1)] public bool WantApply;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper49", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiWindowSettings* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiWindowSettings()
        {
            fixed (ImGuiWindowSettings* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetName@ImGuiWindowSettings@@QEAAPEADXZ", ExactSpelling = true)]
        private static extern byte* GetName_PInvoke(ImGuiWindowSettings* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public byte* GetName()
        {
            fixed (ImGuiWindowSettings* @this = &this)
            { return GetName_PInvoke(@this); }
        }
    }
}
