// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public unsafe partial struct ImGuiNavItemData
    {
        [FieldOffset(0)] public ImGuiWindow* Window;

        [FieldOffset(8)] public uint ID;

        [FieldOffset(12)] public uint FocusScopeId;

        [FieldOffset(16)] public ImRect RectRel;

        [FieldOffset(32)] public ImGuiItemFlags InFlags;

        [FieldOffset(36)] public float DistBox;

        [FieldOffset(40)] public float DistCenter;

        [FieldOffset(44)] public float DistAxial;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper43", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiNavItemData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiNavItemData()
        {
            fixed (ImGuiNavItemData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Clear@ImGuiNavItemData@@QEAAXXZ", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImGuiNavItemData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImGuiNavItemData* @this = &this)
            { Clear_PInvoke(@this); }
        }
    }
}
