// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public unsafe partial struct ImGuiListClipperData
    {
        [FieldOffset(0)] public ImGuiListClipper* ListClipper;

        [FieldOffset(8)] public float LossynessOffset;

        [FieldOffset(12)] public int StepNo;

        [FieldOffset(16)] public int ItemsFrozen;

        [FieldOffset(24)] public ImVector<ImGuiListClipperRange> Ranges;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper42", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiListClipperData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiListClipperData()
        {
            fixed (ImGuiListClipperData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Reset@ImGuiListClipperData@@QEAAXPEAUImGuiListClipper@@@Z", ExactSpelling = true)]
        private static extern void Reset_PInvoke(ImGuiListClipperData* @this, ImGuiListClipper* clipper);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Reset(ImGuiListClipper* clipper)
        {
            fixed (ImGuiListClipperData* @this = &this)
            { Reset_PInvoke(@this, clipper); }
        }
    }
}
