// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 60)]
    public unsafe partial struct ImGuiLastItemData
    {
        [FieldOffset(0)] public uint ID;

        [FieldOffset(4)] public ImGuiItemFlags InFlags;

        [FieldOffset(8)] public ImGuiItemStatusFlags StatusFlags;

        [FieldOffset(12)] public ImRect Rect;

        [FieldOffset(28)] public ImRect NavRect;

        [FieldOffset(44)] public ImRect DisplayRect;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper37", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiLastItemData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiLastItemData()
        {
            fixed (ImGuiLastItemData* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
