// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.DearImGui.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public unsafe partial struct ImGuiStackLevelInfo
    {
        [FieldOffset(0)] public uint ID;

        [FieldOffset(4)] public sbyte QueryFrameCount;

        [FieldOffset(5)] [MarshalAs(UnmanagedType.I1)] public bool QuerySuccess;

        [FieldOffset(6)] public ConstantArray_char_58 Desc;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper52", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStackLevelInfo* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiStackLevelInfo()
        {
            fixed (ImGuiStackLevelInfo* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
