// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 112)]
    public unsafe partial struct ImGuiTableTempData
    {
        [FieldOffset(0)] public int TableIndex;

        [FieldOffset(4)] public float LastTimeActive;

        [FieldOffset(8)] public Vector2 UserOuterSize;

        [FieldOffset(16)] public ImDrawListSplitter DrawSplitter;

        [FieldOffset(40)] public ImRect HostBackupWorkRect;

        [FieldOffset(56)] public ImRect HostBackupParentWorkRect;

        [FieldOffset(72)] public Vector2 HostBackupPrevLineSize;

        [FieldOffset(80)] public Vector2 HostBackupCurrLineSize;

        [FieldOffset(88)] public Vector2 HostBackupCursorMaxPos;

        [FieldOffset(96)] public float HostBackupColumnsOffset;

        [FieldOffset(100)] public float HostBackupItemWidth;

        [FieldOffset(104)] public int HostBackupItemWidthStackSize;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper60", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiTableTempData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiTableTempData()
        {
            fixed (ImGuiTableTempData* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
