// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImGuiMetricsConfig
    {
        [FieldOffset(0)] [MarshalAs(UnmanagedType.I1)] public bool ShowStackTool;

        [FieldOffset(1)] [MarshalAs(UnmanagedType.I1)] public bool ShowWindowsRects;

        [FieldOffset(2)] [MarshalAs(UnmanagedType.I1)] public bool ShowWindowsBeginOrder;

        [FieldOffset(3)] [MarshalAs(UnmanagedType.I1)] public bool ShowTablesRects;

        [FieldOffset(4)] [MarshalAs(UnmanagedType.I1)] public bool ShowDrawCmdMesh;

        [FieldOffset(5)] [MarshalAs(UnmanagedType.I1)] public bool ShowDrawCmdBoundingBoxes;

        [FieldOffset(6)] [MarshalAs(UnmanagedType.I1)] public bool ShowDockingNodes;

        [FieldOffset(8)] public int ShowWindowsRectsType;

        [FieldOffset(12)] public int ShowTablesRectsType;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper51", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiMetricsConfig* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiMetricsConfig()
        {
            fixed (ImGuiMetricsConfig* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
