// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Numerics;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 232)]
    public unsafe partial struct ImGuiWindowTempData
    {
        [FieldOffset(0)] public Vector2 CursorPos;

        [FieldOffset(8)] public Vector2 CursorPosPrevLine;

        [FieldOffset(16)] public Vector2 CursorStartPos;

        [FieldOffset(24)] public Vector2 CursorMaxPos;

        [FieldOffset(32)] public Vector2 IdealMaxPos;

        [FieldOffset(40)] public Vector2 CurrLineSize;

        [FieldOffset(48)] public Vector2 PrevLineSize;

        [FieldOffset(56)] public float CurrLineTextBaseOffset;

        [FieldOffset(60)] public float PrevLineTextBaseOffset;

        [FieldOffset(64)] public float Indent;

        [FieldOffset(68)] public float ColumnsOffset;

        [FieldOffset(72)] public float GroupOffset;

        [FieldOffset(76)] public Vector2 CursorStartPosLossyness;

        [FieldOffset(84)] public ImGuiNavLayer NavLayerCurrent;

        [FieldOffset(88)] public short NavLayersActiveMask;

        [FieldOffset(90)] public short NavLayersActiveMaskNext;

        [FieldOffset(92)] public uint NavFocusScopeIdCurrent;

        [FieldOffset(96)] [MarshalAs(UnmanagedType.I1)] public bool NavHideHighlightOneFrame;

        [FieldOffset(97)] [MarshalAs(UnmanagedType.I1)] public bool NavHasScroll;

        [FieldOffset(98)] [MarshalAs(UnmanagedType.I1)] public bool MenuBarAppending;

        [FieldOffset(100)] public Vector2 MenuBarOffset;

        [FieldOffset(108)] public ImGuiMenuColumns MenuColumns;

        [FieldOffset(136)] public int TreeDepth;

        [FieldOffset(140)] public uint TreeJumpToParentOnPopMask;

        [FieldOffset(144)] public ImGuiWindowVector ChildWindows;

        [FieldOffset(160)] public ImGuiStorage* StateStorage;

        [FieldOffset(168)] public ImGuiOldColumns* CurrentColumns;

        [FieldOffset(176)] public int CurrentTableIdx;

        [FieldOffset(180)] public ImGuiLayoutType LayoutType;

        [FieldOffset(184)] public ImGuiLayoutType ParentLayoutType;

        [FieldOffset(188)] public float ItemWidth;

        [FieldOffset(192)] public float TextWrapPos;

        [FieldOffset(200)] public ImVector<float> ItemWidthStack;

        [FieldOffset(216)] public ImVector<float> TextWrapPosStack;
    }
}
