// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.DearImGui.Internal
{
    public enum ImGuiInputEventType
    {
        ImGuiInputEventType_None = 0,
        ImGuiInputEventType_MousePos,
        ImGuiInputEventType_MouseWheel,
        ImGuiInputEventType_MouseButton,
        ImGuiInputEventType_MouseViewport,
        ImGuiInputEventType_Key,
        ImGuiInputEventType_Char,
        ImGuiInputEventType_Focus,
        ImGuiInputEventType_COUNT
    }
}
