// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.DearImGui.Internal
{
    public enum ImGuiInputSource
    {
        ImGuiInputSource_None = 0,
        ImGuiInputSource_Mouse,
        ImGuiInputSource_Keyboard,
        ImGuiInputSource_Gamepad,
        ImGuiInputSource_Clipboard,
        ImGuiInputSource_Nav,
        ImGuiInputSource_COUNT
    }
}
