// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.DearImGui.Internal
{
    public enum ImGuiKeyPrivate_
    {
        ImGuiKey_LegacyNativeKey_BEGIN = 0,
        ImGuiKey_LegacyNativeKey_END = 512,
        ImGuiKey_Gamepad_BEGIN = 617,
        ImGuiKey_Gamepad_END = 641
    }
}
