// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public unsafe partial struct ImGuiListClipperRange
    {
        [FieldOffset(0)] public int Min;

        [FieldOffset(4)] public int Max;

        [FieldOffset(8)] [MarshalAs(UnmanagedType.I1)] public bool PosToIndexConvert;

        [FieldOffset(9)] public sbyte PosToIndexOffsetMin;

        [FieldOffset(10)] public sbyte PosToIndexOffsetMax;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?FromIndices@ImGuiListClipperRange@@SA?AU1@HH@Z", ExactSpelling = true)]
        private static extern ImGuiListClipperRange* FromIndices_PInvoke(ImGuiListClipperRange* __returnBuffer, int min, int max);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ImGuiListClipperRange FromIndices(int min, int max)
        {
            ImGuiListClipperRange __returnBuffer;

            FromIndices_PInvoke(&__returnBuffer, min, max);

            return __returnBuffer;
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?FromPositions@ImGuiListClipperRange@@SA?AU1@MMHH@Z", ExactSpelling = true)]
        private static extern ImGuiListClipperRange* FromPositions_PInvoke(ImGuiListClipperRange* __returnBuffer, float y1, float y2, int off_min, int off_max);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ImGuiListClipperRange FromPositions(float y1, float y2, int off_min, int off_max)
        {
            ImGuiListClipperRange __returnBuffer;

            FromPositions_PInvoke(&__returnBuffer, y1, y2, off_min, off_max);

            return __returnBuffer;
        }
    }
}
