// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 1)]
    public unsafe partial struct ImGuiInputEventAppFocused
    {
        [FieldOffset(0)] [MarshalAs(UnmanagedType.I1)] public bool Focused;
    }
}
