// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct ImGuiInputEventMouseWheel
    {
        [FieldOffset(0)] public float WheelX;

        [FieldOffset(4)] public float WheelY;
    }
}
