// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Numerics;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public unsafe partial struct ImGuiColorMod
    {
        [FieldOffset(0)] public ImGuiCol Col;

        [FieldOffset(4)] public Vector4 BackupValue;
    }
}
