// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public unsafe partial struct ImGuiInputEventMouseViewport
    {
        [FieldOffset(0)] public uint HoveredViewportID;
    }
}
