// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.DearImGui.Infrastructure;
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public unsafe partial struct ImGuiStyleMod
    {
        [FieldOffset(0)] public ImGuiStyleVar VarIdx;

        [FieldOffset(4)] public (int x, int y) BackupInt;

        [FieldOffset(4)] public Vector2 BackupFloat;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper28", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStyleMod* @this, ImGuiStyleVar idx, int v);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiStyleMod(ImGuiStyleVar idx, int v)
        {
            fixed (ImGuiStyleMod* @this = &this)
            { Constructor_PInvoke(@this, idx, v); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper29", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStyleMod* @this, ImGuiStyleVar idx, float v);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiStyleMod(ImGuiStyleVar idx, float v)
        {
            fixed (ImGuiStyleMod* @this = &this)
            { Constructor_PInvoke(@this, idx, v); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper30", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStyleMod* @this, ImGuiStyleVar idx, Vector2 v);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiStyleMod(ImGuiStyleVar idx, Vector2 v)
        {
            fixed (ImGuiStyleMod* @this = &this)
            { Constructor_PInvoke(@this, idx, v); }
        }
    }
}
