// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImGuiStackTool
    {
        [FieldOffset(0)] public int LastActiveFrame;

        [FieldOffset(4)] public int StackLevel;

        [FieldOffset(8)] public uint QueryId;

        [FieldOffset(16)] public ImVector<ImGuiStackLevelInfo> Results;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper53", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStackTool* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiStackTool()
        {
            fixed (ImGuiStackTool* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
