// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.DearImGui.Infrastructure;
using System;
using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 1088)]
    public unsafe partial struct ImGuiWindow
    {
        [FieldOffset(0)] public byte* Name;

        [FieldOffset(8)] public uint ID;

        [FieldOffset(12)] public ImGuiWindowFlags Flags;

        [FieldOffset(16)] public ImGuiWindowFlags FlagsPreviousFrame;

        [FieldOffset(20)] public ImGuiWindowClass WindowClass;

        [FieldOffset(48)] public ImGuiViewportP* Viewport;

        [FieldOffset(56)] public uint ViewportId;

        [FieldOffset(60)] public Vector2 ViewportPos;

        [FieldOffset(68)] public int ViewportAllowPlatformMonitorExtend;

        [FieldOffset(72)] public Vector2 Pos;

        [FieldOffset(80)] public Vector2 Size;

        [FieldOffset(88)] public Vector2 SizeFull;

        [FieldOffset(96)] public Vector2 ContentSize;

        [FieldOffset(104)] public Vector2 ContentSizeIdeal;

        [FieldOffset(112)] public Vector2 ContentSizeExplicit;

        [FieldOffset(120)] public Vector2 WindowPadding;

        [FieldOffset(128)] public float WindowRounding;

        [FieldOffset(132)] public float WindowBorderSize;

        [FieldOffset(136)] public int NameBufLen;

        [FieldOffset(140)] public uint MoveId;

        [FieldOffset(144)] public uint TabId;

        [FieldOffset(148)] public uint ChildId;

        [FieldOffset(152)] public Vector2 Scroll;

        [FieldOffset(160)] public Vector2 ScrollMax;

        [FieldOffset(168)] public Vector2 ScrollTarget;

        [FieldOffset(176)] public Vector2 ScrollTargetCenterRatio;

        [FieldOffset(184)] public Vector2 ScrollTargetEdgeSnapDist;

        [FieldOffset(192)] public Vector2 ScrollbarSizes;

        [FieldOffset(200)] [MarshalAs(UnmanagedType.I1)] public bool ScrollbarX;

        [FieldOffset(201)] [MarshalAs(UnmanagedType.I1)] public bool ScrollbarY;

        [FieldOffset(202)] [MarshalAs(UnmanagedType.I1)] public bool ViewportOwned;

        [FieldOffset(203)] [MarshalAs(UnmanagedType.I1)] public bool Active;

        [FieldOffset(204)] [MarshalAs(UnmanagedType.I1)] public bool WasActive;

        [FieldOffset(205)] [MarshalAs(UnmanagedType.I1)] public bool WriteAccessed;

        [FieldOffset(206)] [MarshalAs(UnmanagedType.I1)] public bool Collapsed;

        [FieldOffset(207)] [MarshalAs(UnmanagedType.I1)] public bool WantCollapseToggle;

        [FieldOffset(208)] [MarshalAs(UnmanagedType.I1)] public bool SkipItems;

        [FieldOffset(209)] [MarshalAs(UnmanagedType.I1)] public bool Appearing;

        [FieldOffset(210)] [MarshalAs(UnmanagedType.I1)] public bool Hidden;

        [FieldOffset(211)] [MarshalAs(UnmanagedType.I1)] public bool IsFallbackWindow;

        [FieldOffset(212)] [MarshalAs(UnmanagedType.I1)] public bool IsExplicitChild;

        [FieldOffset(213)] [MarshalAs(UnmanagedType.I1)] public bool HasCloseButton;

        [FieldOffset(214)] public sbyte ResizeBorderHeld;

        [FieldOffset(216)] public short BeginCount;

        [FieldOffset(218)] public short BeginOrderWithinParent;

        [FieldOffset(220)] public short BeginOrderWithinContext;

        [FieldOffset(222)] public short FocusOrder;

        [FieldOffset(224)] public uint PopupId;

        [FieldOffset(228)] public sbyte AutoFitFramesX;

        [FieldOffset(229)] public sbyte AutoFitFramesY;

        [FieldOffset(230)] public sbyte AutoFitChildAxises;

        [FieldOffset(231)] [MarshalAs(UnmanagedType.I1)] public bool AutoFitOnlyGrows;

        [FieldOffset(232)] public ImGuiDir AutoPosLastDirection;

        [FieldOffset(236)] public sbyte HiddenFramesCanSkipItems;

        [FieldOffset(237)] public sbyte HiddenFramesCannotSkipItems;

        [FieldOffset(238)] public sbyte HiddenFramesForRenderOnly;

        [FieldOffset(239)] public sbyte DisableInputsFrames;

        [FieldOffset(240)] private uint __SetWindowPosAllowFlags__backingField;
        public ImGuiCond SetWindowPosAllowFlags
        {
            get => (ImGuiCond)((__SetWindowPosAllowFlags__backingField >> 0) & 0xFFU);
            set
            {
                uint shiftedValue = (((uint)value) & 0xFFU) << 0;
                uint otherBits = __SetWindowPosAllowFlags__backingField & 0xFFFFFF00U;
                __SetWindowPosAllowFlags__backingField = otherBits | shiftedValue;
            }
        }

        [FieldOffset(240)] private uint __SetWindowSizeAllowFlags__backingField;
        public ImGuiCond SetWindowSizeAllowFlags
        {
            get => (ImGuiCond)((__SetWindowSizeAllowFlags__backingField >> 8) & 0xFFU);
            set
            {
                uint shiftedValue = (((uint)value) & 0xFFU) << 8;
                uint otherBits = __SetWindowSizeAllowFlags__backingField & 0xFFFF00FFU;
                __SetWindowSizeAllowFlags__backingField = otherBits | shiftedValue;
            }
        }

        [FieldOffset(240)] private uint __SetWindowCollapsedAllowFlags__backingField;
        public ImGuiCond SetWindowCollapsedAllowFlags
        {
            get => (ImGuiCond)((__SetWindowCollapsedAllowFlags__backingField >> 16) & 0xFFU);
            set
            {
                uint shiftedValue = (((uint)value) & 0xFFU) << 16;
                uint otherBits = __SetWindowCollapsedAllowFlags__backingField & 0xFF00FFFFU;
                __SetWindowCollapsedAllowFlags__backingField = otherBits | shiftedValue;
            }
        }

        [FieldOffset(240)] private uint __SetWindowDockAllowFlags__backingField;
        public ImGuiCond SetWindowDockAllowFlags
        {
            get => (ImGuiCond)((__SetWindowDockAllowFlags__backingField >> 24) & 0xFFU);
            set
            {
                uint shiftedValue = (((uint)value) & 0xFFU) << 24;
                uint otherBits = __SetWindowDockAllowFlags__backingField & 0xFFFFFFU;
                __SetWindowDockAllowFlags__backingField = otherBits | shiftedValue;
            }
        }

        [FieldOffset(244)] public Vector2 SetWindowPosVal;

        [FieldOffset(252)] public Vector2 SetWindowPosPivot;

        [FieldOffset(264)] public ImVector<uint> IDStack;

        [FieldOffset(280)] public ImGuiWindowTempData DC;

        [FieldOffset(512)] public ImRect OuterRectClipped;

        [FieldOffset(528)] public ImRect InnerRect;

        [FieldOffset(544)] public ImRect InnerClipRect;

        [FieldOffset(560)] public ImRect WorkRect;

        [FieldOffset(576)] public ImRect ParentWorkRect;

        [FieldOffset(592)] public ImRect ClipRect;

        [FieldOffset(608)] public ImRect ContentRegionRect;

        [FieldOffset(624)] public (short x, short y) HitTestHoleSize;

        [FieldOffset(628)] public (short x, short y) HitTestHoleOffset;

        [FieldOffset(632)] public int LastFrameActive;

        [FieldOffset(636)] public int LastFrameJustFocused;

        [FieldOffset(640)] public float LastTimeActive;

        [FieldOffset(644)] public float ItemWidthDefault;

        [FieldOffset(648)] public ImGuiStorage StateStorage;

        [FieldOffset(664)] public ImVector<ImGuiOldColumns> ColumnsStorage;

        [FieldOffset(680)] public float FontWindowScale;

        [FieldOffset(684)] public float FontDpiScale;

        [FieldOffset(688)] public int SettingsOffset;

        [FieldOffset(696)] public ImDrawList* DrawList;

        [FieldOffset(704)] public ImDrawList DrawListInst;

        [FieldOffset(904)] public ImGuiWindow* ParentWindow;

        [FieldOffset(912)] public ImGuiWindow* ParentWindowInBeginStack;

        [FieldOffset(920)] public ImGuiWindow* RootWindow;

        [FieldOffset(928)] public ImGuiWindow* RootWindowPopupTree;

        [FieldOffset(936)] public ImGuiWindow* RootWindowDockTree;

        [FieldOffset(944)] public ImGuiWindow* RootWindowForTitleBarHighlight;

        [FieldOffset(952)] public ImGuiWindow* RootWindowForNav;

        [FieldOffset(960)] public ImGuiWindow* NavLastChildNavWindow;

        [FieldOffset(968)] public ConstantArray_ImGuiID_2 NavLastIds;

        [FieldOffset(976)] public ConstantArray_ImRect_2 NavRectRel;

        [FieldOffset(1008)] public int MemoryDrawListIdxCapacity;

        [FieldOffset(1012)] public int MemoryDrawListVtxCapacity;

        [FieldOffset(1016)] [MarshalAs(UnmanagedType.I1)] public bool MemoryCompacted;

        [FieldOffset(1017)] private byte __DockIsActive__backingField;
        public bool DockIsActive
        {
            get => ((__DockIsActive__backingField >> 0) & 0x1U) != 0;
            set
            {
                uint shiftedValue = ((value ? 1U : 0U) & 0x1U) << 0;
                uint otherBits = __DockIsActive__backingField & 0xFEU;
                __DockIsActive__backingField = (byte)(otherBits | shiftedValue);
            }
        }

        [FieldOffset(1017)] private byte __DockNodeIsVisible__backingField;
        public bool DockNodeIsVisible
        {
            get => ((__DockNodeIsVisible__backingField >> 1) & 0x1U) != 0;
            set
            {
                uint shiftedValue = ((value ? 1U : 0U) & 0x1U) << 1;
                uint otherBits = __DockNodeIsVisible__backingField & 0xFDU;
                __DockNodeIsVisible__backingField = (byte)(otherBits | shiftedValue);
            }
        }

        [FieldOffset(1017)] private byte __DockTabIsVisible__backingField;
        public bool DockTabIsVisible
        {
            get => ((__DockTabIsVisible__backingField >> 2) & 0x1U) != 0;
            set
            {
                uint shiftedValue = ((value ? 1U : 0U) & 0x1U) << 2;
                uint otherBits = __DockTabIsVisible__backingField & 0xFBU;
                __DockTabIsVisible__backingField = (byte)(otherBits | shiftedValue);
            }
        }

        [FieldOffset(1017)] private byte __DockTabWantClose__backingField;
        public bool DockTabWantClose
        {
            get => ((__DockTabWantClose__backingField >> 3) & 0x1U) != 0;
            set
            {
                uint shiftedValue = ((value ? 1U : 0U) & 0x1U) << 3;
                uint otherBits = __DockTabWantClose__backingField & 0xF7U;
                __DockTabWantClose__backingField = (byte)(otherBits | shiftedValue);
            }
        }

        [FieldOffset(1018)] public short DockOrder;

        [FieldOffset(1020)] public ImGuiWindowDockStyle DockStyle;

        [FieldOffset(1048)] public ImGuiDockNode* DockNode;

        [FieldOffset(1056)] public ImGuiDockNode* DockNodeAsHost;

        [FieldOffset(1064)] public uint DockId;

        [FieldOffset(1068)] public ImGuiItemStatusFlags DockTabItemStatusFlags;

        [FieldOffset(1072)] public ImRect DockTabItemRect;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImGuiWindow@@QEAA@PEAUImGuiContext@@PEBD@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiWindow* @this, ImGuiContext* context, byte* name);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiWindow(ImGuiContext* context, byte* name)
        {
            fixed (ImGuiWindow* @this = &this)
            { Constructor_PInvoke(@this, context, name); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiWindow(ImGuiContext* context, DearImGuiInterpolatedStringHandler name)
        {
            fixed (ImGuiWindow* @this = &this)
            fixed (byte* __nameP = name.NullTerminateAndGetString())
            { Constructor_PInvoke(@this, context, __nameP); }

            name.Dispose();
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??1ImGuiWindow@@QEAA@XZ", ExactSpelling = true)]
        private static extern void Destructor_PInvoke(ImGuiWindow* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (ImGuiWindow* @this = &this)
            { Destructor_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetID@ImGuiWindow@@QEAAIPEBD0@Z", ExactSpelling = true)]
        private static extern uint GetID_PInvoke(ImGuiWindow* @this, byte* str, byte* str_end);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetID(byte* str, byte* str_end = null)
        {
            fixed (ImGuiWindow* @this = &this)
            { return GetID_PInvoke(@this, str, str_end); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetID(DearImGuiInterpolatedStringHandler str)
        {
            uint __result;
            ReadOnlySpan<byte> __str = str.NullTerminateAndGetString();

            fixed (ImGuiWindow* @this = &this)
            fixed (byte* __strP = __str)
            { __result = GetID_PInvoke(@this, __strP, __strP + __str.Length); }

            str.Dispose();
            return __result;
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetID@ImGuiWindow@@QEAAIPEBX@Z", ExactSpelling = true)]
        private static extern uint GetID_PInvoke(ImGuiWindow* @this, void* ptr);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetID(void* ptr)
        {
            fixed (ImGuiWindow* @this = &this)
            { return GetID_PInvoke(@this, ptr); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetID@ImGuiWindow@@QEAAIH@Z", ExactSpelling = true)]
        private static extern uint GetID_PInvoke(ImGuiWindow* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetID(int n)
        {
            fixed (ImGuiWindow* @this = &this)
            { return GetID_PInvoke(@this, n); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetIDNoKeepAlive@ImGuiWindow@@QEAAIPEBD0@Z", ExactSpelling = true)]
        private static extern uint GetIDNoKeepAlive_PInvoke(ImGuiWindow* @this, byte* str, byte* str_end);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetIDNoKeepAlive(byte* str, byte* str_end = null)
        {
            fixed (ImGuiWindow* @this = &this)
            { return GetIDNoKeepAlive_PInvoke(@this, str, str_end); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetIDNoKeepAlive(DearImGuiInterpolatedStringHandler str)
        {
            uint __result;
            ReadOnlySpan<byte> __str = str.NullTerminateAndGetString();

            fixed (ImGuiWindow* @this = &this)
            fixed (byte* __strP = __str)
            { __result = GetIDNoKeepAlive_PInvoke(@this, __strP, __strP + __str.Length); }

            str.Dispose();
            return __result;
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetIDNoKeepAlive@ImGuiWindow@@QEAAIPEBX@Z", ExactSpelling = true)]
        private static extern uint GetIDNoKeepAlive_PInvoke(ImGuiWindow* @this, void* ptr);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetIDNoKeepAlive(void* ptr)
        {
            fixed (ImGuiWindow* @this = &this)
            { return GetIDNoKeepAlive_PInvoke(@this, ptr); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetIDNoKeepAlive@ImGuiWindow@@QEAAIH@Z", ExactSpelling = true)]
        private static extern uint GetIDNoKeepAlive_PInvoke(ImGuiWindow* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetIDNoKeepAlive(int n)
        {
            fixed (ImGuiWindow* @this = &this)
            { return GetIDNoKeepAlive_PInvoke(@this, n); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetIDFromRectangle@ImGuiWindow@@QEAAIAEBUImRect@@@Z", ExactSpelling = true)]
        private static extern uint GetIDFromRectangle_PInvoke(ImGuiWindow* @this, ImRect* r_abs);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint GetIDFromRectangle(in ImRect r_abs)
        {
            fixed (ImGuiWindow* @this = &this)
            fixed (ImRect* __r_absP = &r_abs)
            { return GetIDFromRectangle_PInvoke(@this, __r_absP); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Rect@ImGuiWindow@@QEBA?AUImRect@@XZ", ExactSpelling = true)]
        private static extern ImRect* Rect_PInvoke(ImGuiWindow* @this, ImRect* __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImRect Rect()
        {
            ImRect __returnBuffer;

            fixed (ImGuiWindow* @this = &this)
            { Rect_PInvoke(@this, &__returnBuffer); }

            return __returnBuffer;
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?CalcFontSize@ImGuiWindow@@QEBAMXZ", ExactSpelling = true)]
        private static extern float CalcFontSize_PInvoke(ImGuiWindow* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float CalcFontSize()
        {
            fixed (ImGuiWindow* @this = &this)
            { return CalcFontSize_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?TitleBarHeight@ImGuiWindow@@QEBAMXZ", ExactSpelling = true)]
        private static extern float TitleBarHeight_PInvoke(ImGuiWindow* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float TitleBarHeight()
        {
            fixed (ImGuiWindow* @this = &this)
            { return TitleBarHeight_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?TitleBarRect@ImGuiWindow@@QEBA?AUImRect@@XZ", ExactSpelling = true)]
        private static extern ImRect* TitleBarRect_PInvoke(ImGuiWindow* @this, ImRect* __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImRect TitleBarRect()
        {
            ImRect __returnBuffer;

            fixed (ImGuiWindow* @this = &this)
            { TitleBarRect_PInvoke(@this, &__returnBuffer); }

            return __returnBuffer;
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?MenuBarHeight@ImGuiWindow@@QEBAMXZ", ExactSpelling = true)]
        private static extern float MenuBarHeight_PInvoke(ImGuiWindow* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float MenuBarHeight()
        {
            fixed (ImGuiWindow* @this = &this)
            { return MenuBarHeight_PInvoke(@this); }
        }

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?MenuBarRect@ImGuiWindow@@QEBA?AUImRect@@XZ", ExactSpelling = true)]
        private static extern ImRect* MenuBarRect_PInvoke(ImGuiWindow* @this, ImRect* __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImRect MenuBarRect()
        {
            ImRect __returnBuffer;

            fixed (ImGuiWindow* @this = &this)
            { MenuBarRect_PInvoke(@this, &__returnBuffer); }

            return __returnBuffer;
        }
    }
}
