// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace Mochi.DearImGui.Internal
{
    [Flags]
    public enum ImGuiTooltipFlags
    {
        None = 0,
        OverridePreviousTooltip = 1
    }
}
