// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.DearImGui.Internal
{
    public enum ImGuiInputTextFlagsPrivate_
    {
        ImGuiInputTextFlags_Multiline = 67108864,
        ImGuiInputTextFlags_NoMarkEdited = 134217728,
        ImGuiInputTextFlags_MergedItem = 268435456
    }
}
