// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public unsafe partial struct ImGuiInputEventKey
    {
        [FieldOffset(0)] public ImGuiKey Key;

        [FieldOffset(4)] [MarshalAs(UnmanagedType.I1)] public bool Down;

        [FieldOffset(8)] public float AnalogValue;
    }
}
