// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.DearImGui.Internal
{
    public enum ImGuiSelectableFlagsPrivate_
    {
        ImGuiSelectableFlags_NoHoldingActiveID = 1048576,
        ImGuiSelectableFlags_SelectOnNav = 2097152,
        ImGuiSelectableFlags_SelectOnClick = 4194304,
        ImGuiSelectableFlags_SelectOnRelease = 8388608,
        ImGuiSelectableFlags_SpanAvailWidth = 16777216,
        ImGuiSelectableFlags_DrawHoveredWhenHeld = 33554432,
        ImGuiSelectableFlags_SetNavIdOnHover = 67108864,
        ImGuiSelectableFlags_NoPadWithHalfSpacing = 134217728
    }
}
