// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.DearImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public unsafe partial struct ImGuiTabItem
    {
        [FieldOffset(0)] public uint ID;

        [FieldOffset(4)] public ImGuiTabItemFlags Flags;

        [FieldOffset(8)] public ImGuiWindow* Window;

        [FieldOffset(16)] public int LastFrameVisible;

        [FieldOffset(20)] public int LastFrameSelected;

        [FieldOffset(24)] public float Offset;

        [FieldOffset(28)] public float Width;

        [FieldOffset(32)] public float ContentWidth;

        [FieldOffset(36)] public int NameOffset;

        [FieldOffset(40)] public short BeginOrder;

        [FieldOffset(42)] public short IndexDuringLayout;

        [FieldOffset(44)] [MarshalAs(UnmanagedType.I1)] public bool WantClose;

        [DllImport("Mochi.DearImGui.Native", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper56", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiTabItem* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiTabItem()
        {
            fixed (ImGuiTabItem* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
