// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace Mochi.DearImGui.Internal
{
    [Flags]
    public enum ImGuiNavDirSourceFlags
    {
        None = 0,
        RawKeyboard = 1,
        Keyboard = 2,
        PadDPad = 4,
        PadLStick = 8
    }
}
