name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish  /p:SelfContained=true -r win-x64 -c release
    - name: Compress
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
        Compress-Archive -Path D:\a\Imgui_CSharp\Imgui_CSharp\testnative\bin\Release\net6.0\win-x64\publish\* -DestinationPath C:\builtfiles\Imgui_CSharp.zip

    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      with:
        name: Imgui_CSharp
        path: C:\builtfiles\Imgui_CSharp.zip
        if-no-files-found: error
